#!/bin/bash

echo Setting Locale
localedef -f UTF-8 -i en_US en_US.UTF-8

echo Setting Up Network
sudo systemctl enable dhcpcd@enp0s31f6.service
sudo start dhcpcd@enp0s31f6.service

sudo pacman -S ifplugd
#replace enp3s0 with the identifier of your network interface.
sudo systemctl enable netctl-ifplugd@enp0s31f6.service
sudo systemctl start netctl-ifplugd@enp0s31f6.service

echo Installing Base Programs
sudo pacman -S unrar p7zip perl-anyevent-i3 fortune-mod rsync ntfs-3g rtorrent syncthing lxappearance ttf-roboto w3m pavucontrol pulseaudio htop cmatrix openssh xorg-xsetroot os-prober alsa-utils xorg-xrandr vlc feh xorg-xinit xarchiver pcmanfm libreoffice-fresh gparted net-tools git compton xorg ttf-symbola ttf-font-awesome rofi wireless_tools pulseaudio firefox pulseaudio-alsa libmpdclient zip unzip termite

echo Install Virtual Utils
sudo pacman -S qemu virt-manager virtviewer dnsmasq iptables vde2 bridge-utils openbsd-netcat ebtables iptables

echo Installing Codecs
sudo pacman -S a52dec x264 x265 faac faad2 flac jasper lame libdca libdv libmad libmpeg2 libtheora libvorbis libxv wavpack x264 xvidcore gstreamer gst-plugins-ugly gst-plugins-base gst-plugins-bad gst-libav

echo Installing Video Drivers
sudo pacman -S xf86-video-vesa xf86-video-ati mesa mesa-libgl lib32-mesa lib32-mesa-libgl

git clone https://aur.archlinux.org/package-query.git
cd package-query
makepkg -si
cd ..
git clone https://aur.archlinux.org/yaourt.git
cd yaourt
makepkg -si

echo Installing AUR Packages
yaourt -S i3-gaps polybar ttf-font-awesome siji-git mpd-git ncmpcpp-git cava python-pywal-git torrench arch-wiki-cli oomox-git

echo Updating System
sudo pacman -Syu

echo Creating Mount Folders Media, Media2, Data
sudo mkdir /mnt/Media
sudo mkdir /mnt/Media2
sudo mkdir /mnt/Data
sudo mkdir /mnt/usb

echo Setting Up Git Identity
git config --global user.name "Kory Freese"
git config --global user.email koryfreese@gmail.com

echo Disable Screen Timeout
xset -dpms
xset s off
