#!/bin/bash

########################################################
#                    Base Install                      #
########################################################
# mount /dev/sda2 /mnt
# mkdir -p /mnt/boot && mount /dev/sda1 /mnt/boot
# pacstrap /mnt base base-devel
# genfstab -U -p /mnt >> /mnt/etc/fstab
# sed -i -e "s|rw,relatime,data=ordered|rw,relatime,data=ordered,discard|g" /etc/fstab
# arch-chroot /mnt
# echo mac > /etc/hostname

########################################################
#                       Locale                         #
########################################################

echo Setting Locale
sed -i -e "s|#en_US.UTF-8 UTF-8|en_US.UTF-8 UTF-8|g" /etc/locale.gen
sed -i -e "s|#de_CH.UTF-8 UTF-8|de_CH.UTF-8 UTF-8|g" /etc/locale.gen
locale-gen
echo LANG=en_US.UTF-8 > /etc/locale.conf

########################################################
#                     Update System                    #
########################################################

sudo pacman -Syu --noconfirm

########################################################
#                         Network                      #
########################################################

# echo Setting Up Network
# sudo systemctl enable dhcpcd@enp0s31f6.service
# sudo systemctl start dhcpcd@enp0s31f6.service

# sudo pacman -S ifplugd --noconfirm
# #replace enp3s0 with the identifier of your network interface.
# sudo systemctl enable netctl-ifplugd@enp0s31f6.service
# sudo systemctl start netctl-ifplugd@enp0s31f6.service

########################################################
#                         Time                         #
########################################################
rm /etc/localtime
ln -s /usr/share/zoneinfo/Zone/SubZone /etc/localtime
hwclock --systohc --utc
sudo pacman -S ntp --noconfirm
sudo systemctl enable ntpd.service
sudo systemctl enable ntpdate.service

########################################################
#                                         #
########################################################

echo Installing Base Programs
sudo pacman -S klavaro neovim  jsoncpp  udisks2  perl-anyevent-i3 fortune-mod syncthing  w3m  htop cmatrix openssh  feh libreoffice-fresh gparted net-tools git   rofi  libmpdclient --noconfirm

i3lock scrot rhash cmake lib32-dbus


Sudo pacman -S intel-ucode unclutter wmctrl ntfs-3g xorg-xsetroot os-prober xorg-xrandr xorg-xinit gparted wireless_tools pv compton xorg

dunst
mousepad


Sudo pacman -S mpv mpc 


# Sudo pacman -S wine wine_gecko wine-mono


Sudo pacman -S unrar p7zip rsync xarchiver pcmanfm ranger unzip zip


Sudo pacman -S lxappearance ttf-roboto ttf-symbola ttf-font-awesome 


Sudo pacman -S pavucontrol pulseaudio alsa-utils 


Sudo pacman -S fortune-mod 


sudo pacman -S neovim 


sudo pacman -S java-openjfx 




########################################################
#                        Fonts                         #
########################################################




echo Install Virtual Utils
sudo pacman -S qemu virt-manager virtviewer dnsmasq iptables vde2 bridge-utils openbsd-netcat ebtables iptables --noconfirm


########################################################
#                       Codecs                         #
########################################################

echo Installing Codecs
sudo pacman -S a52dec x264 x265 faac faad2 flac jasper lame libdca libdv libmad libmpeg2 libtheora libvorbis libxv wavpack x264 xvidcore gstreamer gst-plugins-ugly gst-plugins-base gst-plugins-bad gst-libav --noconfirm

########################################################
#                   Video Drivers                      #
########################################################

# echo Installing Video Drivers
# sudo pacman -S xf86-video-vesa xf86-video-ati mesa mesa-libgl lib32-mesa lib32-mesa-libgl --noconfirm

########################################################
#                       Yaourt                         #
########################################################

echo Installing Yaourt
git clone https://aur.archlinux.org/package-query.git
cd package-query
makepkg -si
cd ..
git clone https://aur.archlinux.org/yaourt.git
cd yaourt
makepkg -si

########################################################
#                    AUR Packages                      #
########################################################

echo Installing AUR Packages
yaourt -S rxvt-unicode-patched unclutter-xfixes-git firefox-nightly woeusb-giti3-gaps polybar ttf-font-awesome siji-git mpd-git ncmpcpp-git cava python-pywal-git torrench arch-wiki-cli oomox-git tty-clock filebot --noconfirm

########################################################
#                       Updates                        #
########################################################

sudo pacman -Syu

########################################################
#                    Mount Points                      #
########################################################

# echo Creating Mount Folders Media, Media2, Data
# sudo mkdir /mnt/media
# sudo mkdir /mnt/media2
# sudo mkdir /mnt/data
# sudo mkdir /mnt/usb

########################################################
#                    Git Identity                      #
########################################################

echo Setting Up Git Identity
git config --global user.name "Jay Péclard"
git config --global user.email jay.peclard@gmail.com

########################################################
#                Disable Screen Timeout                #
########################################################

echo Disable Screen Timeout
xset -dpms
xset s off

curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Mouse

# sudo pacman -S python-pyside --noconfirm
# yaourt -S razercfg-git --noconfirm
# sudo systemctl enable razerd.service
