#!/bin/bash

echo Cursor Themes Restored
cp -r ~/RICE/Themes/.icons ~/

echo GTK Themes Restored
cp -r ~/RICE/Themes/.themes ~/

echo Xorg Startup Restored
cp ~/RICE/Configs/Xorg/.xinitrc ~/

echo ZSH Config Restored
cp ~/RICE/Configs/zsh/.zshrc ~/

echo Albert Config Restored
cp ~/RICE/Configs/Albert/albert.conf ~/.config/albert/

echo User Dirs Restored
cp ~/RICE/Configs/Dirs/user-dirs.dirs ~/.config/

echo Fonts Restored
cp -r ~/RICE/Themes/fonts ~/.local/share/

echo Deluge Config Restored
rm -rf ~/.config/deluge
cp -r ~/RICE/Configs/Deluge ~/.config/deluge

echo i3 Config Restored
cp ~/RICE/Configs/i3/config ~/.config/i3/

echo XFCE4-Terminal Config Restored
cp ~/RICE/Configs/xfce4-terminal/terminalrc ~/.config/xfce4/terminal/

chsh -s $(which zsh)

echo DONE!
