#!/bin/bash

# .config
cp -r ~/.config/mpv ~/rice/config/.config/
cp -r ~/.config/cava ~/rice/config/.config/
cp -r ~/.config/htop ~/rice/config/.config/
cp -r ~/.config/i3 ~/rice/config/.config/
cp -r ~/.config/neofetch ~/rice/config/.config/
cp -r ~/.config/pcmanfm ~/rice/config/.config/
cp -r ~/.config/polybar ~/rice/config/.config/
cp -r ~/.config/ranger ~/rice/config/.config/
cp -r ~/.config/termite ~/rice/config/.config/
cp -r ~/.config/torrench ~/rice/config/.config/
cp ~/.oh-my-zsh/themes/sublime.zsh-theme ~/rice/config/home/.oh-my-zsh/themes/
# ~/
cp -r ~/.mpd ~/rice/config/home/
cp -r ~/.mplayer ~/rice/config/home/
cp -r ~/.ncmpcpp ~/rice/config/home/
cp -r ~/.themes ~/rice/config/home/
cp -r ~/.icons ~/rice/config/home/
cp -r ~/.local/share/fonts ~/rice/config/home/.local/share
cp -r ~/.i3 ~/rice/config/home/
cp  ~/.gitconfig ~/rice/config/home/
cp  ~/.compton.conf ~/rice/config/home/
cp  ~/.vimrc ~/rice/config/home/
cp  ~/.rtorrent.rc ~/rice/config/home/
cp  ~/.Xauthority ~/rice/config/home/
cp  ~/.xinitrc ~/rice/config/home/
cp  ~/.Xresources ~/rice/config/home/
cp  ~/.zshrc ~/rice/config/home/
cp -r ~/.vim ~/rice/config/home
cp -r ~/.config/dunst ~/rice/config/.config/
cp ~/.config/user-dirs.dirs ~/rice/config/.config/
echo Backup Complete
