#!/bin/bash

echo Cursor Themes Backed Up
cp -r ~/.icons ~/RICE/Themes/

echo GTK Themes Backed Up
cp -r ~/.themes ~/RICE/Themes/

echo Xorg Startup Backed Up
cp ~/.xinitrc ~/RICE/Configs/Xorg/

echo ZSH Config Backed Up
cp ~/.zshrc ~/RICE/Configs/zsh/

echo Albert Config Backed Up
cp ~/.config/albert/albert.conf ~/RICE/Configs/Albert/

echo Fonts Backed Up
cp -r ~/.local/share/fonts ~/RICE/Themes/fonts

echo Deluge Config Backed Up
cp -r ~/.config/deluge/* ~/RICE/Configs/Deluge

echo Backed Up i3 Config
cp ~/.config/i3/config ~/RICE/Configs/i3

echo Backed Up XFCE4-Terminal Config
cp ~/.config/xfce4/terminal/terminalrc ~/RICE/Configs/xfce4-terminal/
