#!/bin/bash

# a system info script written by yours truly
# it's hardcoded stuff, lulz

red="\e[31m"
grn="\e[32m"
ylw="\e[33m"
cyn="\e[36m"
blu="\e[34m"
prp="\e[35m"
bprp="\e[35;1m"
rst="\e[0m"

echo

color-echo()
{  # print with colors
  echo -e " $red$1  $rst$2"
}

# kernel
echo
color-echo 'kernel' "$(uname -smr)"

# shell
color-echo 'Shell ' 'ZSH'

# wm
color-echo 'WM    ' 'I3 Gaps'

# distro
color-echo 'Distro' 'Arch v9k'

# ascii art
echo -e "        "
echo -e " (-_-) Sublime"
echo -e "        "

# colors
echo -e " $red●$rst $grn●$rst $blu●$rst $ylw●$rst $cyn●$rst $prp●$rst $bprp●$rst"

echo
echo

