#!/bin/python
# -*- coding: utf-8 -*-

import requests

CITY = "5368361"
API_KEY = "cd0418adf5567a151c25454dc457b8fc"
UNITS = "Imperial)"
UNIT_KEY = "F"

REQ = requests.get("http://api.openweathermap.org/data/2.5/weather?id={}&appid={}&units={}".format(CITY, 
API_KEY, UNITS))
if REQ.status_code == 200:
    CURRENT = REQ.json()["weather"][0]["description"].capitalize()
    TEMP = int(float(REQ.json()["main"]["temp"]))
print("{}, {} °{}".format(CURRENT, TEMP, UNIT_KEY))
